# 应用名称
spring:
 application:
  name: managementsys
 mvc:
  view:
   prefix: /WEB-INF/jsp/
   suffix: .jsp
  static-path-pattern: /statics/**
 resources:
   static-locations: classpath:/statics/
 profiles:
   active: dev
mybatis:
 #Mapper映射文件的位置
 mapper-locations: classpath:dao/**/*.xml
 #需要起别名的所在包的位置
 type-aliases-package: cn.whyx.pojo
# 应用服务 WEB 访问端口
server:
 port: 8090
